### ISSUE TITLE
Set up intercept recruiter on pilot forest fuelwood page

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/USFS-timber-permitting#12]
**Background**
We want to see about recruiting usability test participants using an intercept form. We may also want to use the form to ask other kinds of Qs. 

**Acceptance criteria** 
- [ ] Users can indicate their willingness to participate and securely submit contact info
- [ ] 18F team can access form responses and contact info 

**Tasks**
- [x] Get analytics for pilot forest fuelwood page. If traffic is historically very low at this time of year, archive this story. 
- [x] Meet with Rob (FS web person) to talk about feasibility
- [ ] Decide on modal, content, and fields for request form
- [ ] Get recruiter code snippet from OPP
- [ ] Tailor copy in template code snippet
- [ ] Send snippet to Rob to add to the site

**Definition of done**
- [ ]  Acceptance criteria met
- [ ] User acceptance tested by at least one teammate

**Comment by MelissaBraxton** [comment]
On 10/24, I emailed Donovan to see about meeting to discuss.

**Comment by MelissaBraxton** [comment]
Chat with Rob at USFS scheduled for 11/8.

**Comment by MelissaBraxton** [comment]
We met with Rob on 11/7. We went over what we want to do and an example. Also sent him candidate pages to look into analytics. We've scheduled a follow up mtg with him for 11/15. 

Candidate pages: 

https://www.fs.usda.gov/main/ocala/passes-permits/forestproducts
https://www.fs.usda.gov/detail/gwj/passes-permits/forestproducts/?cid=fseprd479162
https://www.fs.usda.gov/main/r3/passes-permits/forestproducts
https://www.fs.usda.gov/detail/santafe/passes-permits/forestproducts/?cid=stelprdb5365606
https://www.fs.usda.gov/main/cibola/passes-permits/forestproducts
https://www.fs.usda.gov/detail/gila/passes-permits/forestproducts/?cid=fse_006218
https://www.fs.usda.gov/main/lincoln/passes-permits/forestproducts

**Comment by MelissaBraxton** [comment]
<img width="1440" alt="Screen Shot 2019-11-07 at 2 34 36 PM" src="https://user-images.githubusercontent.com/20651166/68433712-10501180-016c-11ea-8e10-862da3e60eb1.png">
<img width="1440" alt="Screen Shot 2019-11-07 at 2 34 44 PM" src="https://user-images.githubusercontent.com/20651166/68433725-17771f80-016c-11ea-9c92-df546387f703.png">

**Comment by MelissaBraxton** [comment]
Examples above ^

**Comment by MelissaBraxton** [comment]
This meeting has been postponed again. We did however get analytics from Rob that we need to review.

**Comment by MelissaBraxton** [comment]
Emailed Rob to reschedule on 11/25/19
