### ISSUE TITLE
Deliver engagement planning training to Beth

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/USFS-timber-permitting#14]
**Background**
As part of our work to help build product management capacity in the Forest Service and to ensure future success of this work, we need to help FS product personnel develop a strategy to engage stakeholders so that they don't unintentionally create blockers to their modernization goals. 

**Acceptance criteria** 
- [ ] Training has been delivered

**Tasks**
- [ ] Schedule time with Beth and Nikki
- [ ] Develop training material

**Definition of done**
- [ ]  PM approved

**Comment by MelissaBraxton** [comment]
@bboddiger - Realizing "PM approved" may not need to be part of the def of done, but you want to take a look at check this off?

**Comment by annepetersen** [comment]
@bboddiger - Just checking in to see if you saw this. Thanks!
