### ISSUE TITLE
Research team does initial brain dump following field visit

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/USFS-timber-permitting#21]
**Background**
We want to make sure we document our hot takes from the research while they're still fresh in our minds. 

**Acceptance criteria** 
- [ ] Research hot takes are documented in a shareable format

**Tasks**
- [ ] Christine, Mark, and Melissa meet to externalize research insights
- [ ] Document hot takes in a shareable format (GDocs or Mural, etc.)

**Definition of done**
- [ ]  Meets acceptance criteria
