### ISSUE TITLE
Determine whether there are opportunities to leverage TIM API work

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/USFS-timber-permitting#42]
**Background**
We heard that there may be a contractor already working on an API with TIM via Mulesoft. WE may be able to leverage this work!

**Acceptance criteria** 
- [ ] We know the current status of the TIM API
- [ ] We've determined whether to pursue ongoing collaboration

**Tasks**
- [ ] Email Zahid for introduction to person working on TIM API
- [ ] Schedule mtg with that person
- [ ] Meet with that person

**Definition of done**
- [ ]  Acceptance criteria met
- [ ]
