### ISSUE TITLE
1 hour of Mulesoft research

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/USFS-timber-permitting#43]
**Background**
We heard a rumor from Zahid that there may be someone in NRM who is working on using Mulesoft to create an API to interface with TIM. We want to understand how easy Mulesoft is to work with and whether leveraging any work to date on using Mulesoft to connect to TIM could help us.  

**Acceptance criteria** 
- [ ] We have a basic understanding of Mulesoft strengths and weaknesses and whether it could be used with our project. 

**Tasks**
- [ ] Spend one hour researching Mulesoft capabilities online. 

**Definition of done**
- [ ]  Meets acceptance criteria

**Comment by ctro** [comment]
Mulesoft is COTS software that lets you point/click APIs into existence (among other things).
It will display all usual pros/cons of COTS software.

If the partner already has this Mulesoft API thing, we should probably try to use it.
If they need to buy it, maybe not.

I talked to Peter Burkholder who has some experience:
> It seems to be a potential antipattern to overload mulesoft with business logic. But I didn't get to work with it as HUD went south after that.

**Comment by MelissaBraxton** [comment]
Good to know Clint! If you feel like you have an understanding of how it works, strengths/weaknesses, can close this out?
